In [1]:
import pandas as pd

df = pd.read_csv("googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [22]:
df[["Date", "Year"]] = df["Last Updated"].str.split(pat=",", expand=True)
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Date,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,January 7,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,January 15,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,August 1,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,June 8,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,June 20,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,July 25,2017
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,July 6,2018
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,January 20,2017
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,January 19,2015
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,July 25,2018

In [6]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [3]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [23]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Date,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,January 7,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,January 15,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,August 1,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,June 8,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,June 20,2018

In [70]:
years = [2017, 2018]
df1 =  
df1.head()
# for year in years:

Empty DataFrame
Columns: [Category, Year]
Index: []

In [96]:
df['Last Updated'].value_counts(['Category', 'Year'], sort=False)

December 10, 2015    0.000092
May 18, 2017         0.000646
August 18, 2015      0.000184
January 11, 2014     0.000184
February 21, 2017    0.000738
                       ...
May 6, 2013          0.000277
April 25, 2014       0.000092
October 26, 2016     0.000461
May 27, 2017         0.000184
March 25, 2016       0.000184
Name: Last Updated, Length: 1378, dtype: float64

In [98]:
# Sum up count of last updated for year and category
df1 = df.groupby(['Category','Year'])['Year'].count().reset_index(name="Count")
# df1.to_frame()
df1

              Category   Year  Count
0       ART_AND_DESIGN   2017     12
1       ART_AND_DESIGN   2018     53
2    AUTO_AND_VEHICLES   2014      1
3    AUTO_AND_VEHICLES   2016      3
4    AUTO_AND_VEHICLES   2017      7
..                 ...    ...    ...
183            WEATHER   2014      6
184            WEATHER   2015      2
185            WEATHER   2016      2
186            WEATHER   2017     10
187            WEATHER   2018     61

[188 rows x 3 columns]

In [99]:
df1.columns

Index(['Category', 'Year', 'Count'], dtype='object')

In [107]:
final_df = df1.pivot(index='Category', columns='Year', values='Count')
final_df

Year,2010,2011,2012,2013,2014,2015,2016,2017,2018
Category,,,,,,,,,
ART_AND_DESIGN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,53.0
AUTO_AND_VEHICLES,NaN,NaN,NaN,NaN,1.0,NaN,3.0,7.0,74.0
BEAUTY,NaN,NaN,NaN,NaN,NaN,NaN,1.0,12.0,40.0
BOOKS_AND_REFERENCE,NaN,1.0,NaN,3.0,9.0,23.0,27.0,51.0,117.0
BUSINESS,NaN,1.0,1.0,4.0,7.0,24.0,38.0,84.0,301.0
COMICS,NaN,NaN,NaN,NaN,NaN,1.0,1.0,8.0,50.0
COMMUNICATION,NaN,NaN,1.0,3.0,10.0,20.0,23.0,56.0,274.0
DATING,NaN,NaN,NaN,NaN,NaN,NaN,3.0,19.0,212.0
EDUCATION,NaN,NaN,NaN,1.0,3.0,5.0,10.0,26.0,111.0
ENTERTAINMENT,NaN,NaN,NaN,NaN,NaN,3.0,2.0,2.0,142.0
EVENTS,NaN,NaN,NaN,NaN,NaN,NaN,2.0,16.0,46.0
FAMILY,1.0,1.0,9.0,17.0,41.0,103.0,211.0,452.0,1137.0
FINANCE,NaN,NaN,1.0,3.0,NaN,5.0,14.0,48.0,295.0
FOOD_AND_DRINK,NaN,NaN,NaN,NaN,NaN,NaN,5.0,8.0,114.0
GAME,NaN,4.0,2.0,18.0,26.0,62.0,80.0,186.0,766.0
HEALTH_AND_FITNESS,NaN,NaN,2.0,1.0,3.0,9.0,16.0,36.0,274.0
HOUSE_AND_HOME,NaN,NaN,NaN,1.0,NaN,7.0,2.0,10.0,68.0
LIBRARIES_AND_DEMO,NaN,1.0,1.0,2.0,1.0,2.0,7.0,35.0,36.0
LIFESTYLE,NaN,1.0,NaN,3.0,7.0,18.0,40.0,90.0,223.0
MAPS_AND_NAVIGATION,NaN,NaN,NaN,3.0,1.0,3.0,5.0,21.0,104.0
MEDICAL,NaN,NaN,3.0,7.0,15.0,18.0,24.0,88.0,308.0
NEWS_AND_MAGAZINES,NaN,NaN,NaN,NaN,5.0,6.0,15.0,34.0,223.0
PARENTING,NaN,NaN,NaN,NaN,NaN,NaN,2.0,7.0,51.0
PERSONALIZATION,NaN,NaN,NaN,16.0,17.0,24.0,62.0,56.0,217.0
PHOTOGRAPHY,NaN,NaN,1.0,NaN,5.0,15.0,23.0,72.0,219.0
PRODUCTIVITY,NaN,NaN,1.0,5.0,12.0,20.0,37.0,66.0,283.0
SHOPPING,NaN,NaN,1.0,1.0,NaN,3.0,7.0,21.0,227.0
SOCIAL,NaN,NaN,NaN,2.0,4.0,10.0,17.0,37.0,225.0
SPORTS,NaN,NaN,NaN,4.0,4.0,9.0,17.0,59.0,291.0
TOOLS,NaN,6.0,3.0,10.0,26.0,49.0,75.0,180.0,494.0
TRAVEL_AND_LOCAL,NaN,NaN,NaN,1.0,2.0,6.0,19.0,30.0,200.0
VIDEO_PLAYERS,NaN,NaN,NaN,4.0,4.0,12.0,14.0,28.0,113.0
WEATHER,NaN,NaN,NaN,1.0,6.0,2.0,2.0,10.0,61.0

In [108]:
final_df.columns

Index([' 2010', ' 2011', ' 2012', ' 2013', ' 2014', ' 2015', ' 2016', ' 2017',
       ' 2018'],
      dtype='object', name='Year')

In [110]:
final_df = final_df[[' 2017', ' 2018']]
curr = final_df[' 2018']
prev = final_df[' 2017']
final_df['Popularity'] = (curr - prev) / prev
final_df

/Users/allard/anaconda3/envs/ml/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

Year                  2017    2018  Popularity
Category
ART_AND_DESIGN        12.0    53.0    3.416667
AUTO_AND_VEHICLES      7.0    74.0    9.571429
BEAUTY                12.0    40.0    2.333333
BOOKS_AND_REFERENCE   51.0   117.0    1.294118
BUSINESS              84.0   301.0    2.583333
COMICS                 8.0    50.0    5.250000
COMMUNICATION         56.0   274.0    3.892857
DATING                19.0   212.0   10.157895
EDUCATION             26.0   111.0    3.269231
ENTERTAINMENT          2.0   142.0   70.000000
EVENTS                16.0    46.0    1.875000
FAMILY               452.0  1137.0    1.515487
FINANCE               48.0   295.0    5.145833
FOOD_AND_DRINK         8.0   114.0   13.250000
GAME                 186.0   766.0    3.118280
HEALTH_AND_FITNESS    36.0   274.0    6.611111
HOUSE_AND_HOME        10.0    68.0    5.800000
LIBRARIES_AND_DEMO    35.0    36.0    0.028571
LIFESTYLE             90.0   223.0    1.477778
MAPS_AND_NAVIGATION   21.0   104.0    3.952381
MEDICAL               88.0   308.0    2.500000
NEWS_AND_MAGAZINES    34.0   223.0    5.558824
PARENTING              7.0    51.0    6.285714
PERSONALIZATION       56.0   217.0    2.875000
PHOTOGRAPHY           72.0   219.0    2.041667
PRODUCTIVITY          66.0   283.0    3.287879
SHOPPING              21.0   227.0    9.809524
SOCIAL                37.0   225.0    5.081081
SPORTS                59.0   291.0    3.932203
TOOLS                180.0   494.0    1.744444
TRAVEL_AND_LOCAL      30.0   200.0    5.666667
VIDEO_PLAYERS         28.0   113.0    3.035714
WEATHER               10.0    61.0    5.100000

In [111]:
final_df.to_csv('popularity.csv')

In [1]:
import pandas as pd

df2 = pd.read_csv("popularity.csv")
df2

               Category   2017    2018  Popularity
0        ART_AND_DESIGN   12.0    53.0    3.416667
1     AUTO_AND_VEHICLES    7.0    74.0    9.571429
2                BEAUTY   12.0    40.0    2.333333
3   BOOKS_AND_REFERENCE   51.0   117.0    1.294118
4              BUSINESS   84.0   301.0    2.583333
5                COMICS    8.0    50.0    5.250000
6         COMMUNICATION   56.0   274.0    3.892857
7                DATING   19.0   212.0   10.157895
8             EDUCATION   26.0   111.0    3.269231
9         ENTERTAINMENT    2.0   142.0   70.000000
10               EVENTS   16.0    46.0    1.875000
11               FAMILY  452.0  1137.0    1.515487
12              FINANCE   48.0   295.0    5.145833
13       FOOD_AND_DRINK    8.0   114.0   13.250000
14                 GAME  186.0   766.0    3.118280
15   HEALTH_AND_FITNESS   36.0   274.0    6.611111
16       HOUSE_AND_HOME   10.0    68.0    5.800000
17   LIBRARIES_AND_DEMO   35.0    36.0    0.028571
18            LIFESTYLE   90.0   223.0    1.477778
19  MAPS_AND_NAVIGATION   21.0   104.0    3.952381
20              MEDICAL   88.0   308.0    2.500000
21   NEWS_AND_MAGAZINES   34.0   223.0    5.558824
22            PARENTING    7.0    51.0    6.285714
23      PERSONALIZATION   56.0   217.0    2.875000
24          PHOTOGRAPHY   72.0   219.0    2.041667
25         PRODUCTIVITY   66.0   283.0    3.287879
26             SHOPPING   21.0   227.0    9.809524
27               SOCIAL   37.0   225.0    5.081081
28               SPORTS   59.0   291.0    3.932203
29                TOOLS  180.0   494.0    1.744444
30     TRAVEL_AND_LOCAL   30.0   200.0    5.666667
31        VIDEO_PLAYERS   28.0   113.0    3.035714
32              WEATHER   10.0    61.0    5.100000

In [6]:
df2["Popularity"] = df2["Popularity"].round(2)

In [10]:
df2 = df2.sort_values(by="Popularity")
df2

               Category   2017    2018  Popularity
17   LIBRARIES_AND_DEMO   35.0    36.0        0.03
3   BOOKS_AND_REFERENCE   51.0   117.0        1.29
18            LIFESTYLE   90.0   223.0        1.48
11               FAMILY  452.0  1137.0        1.52
29                TOOLS  180.0   494.0        1.74
10               EVENTS   16.0    46.0        1.88
24          PHOTOGRAPHY   72.0   219.0        2.04
2                BEAUTY   12.0    40.0        2.33
20              MEDICAL   88.0   308.0        2.50
4              BUSINESS   84.0   301.0        2.58
23      PERSONALIZATION   56.0   217.0        2.88
31        VIDEO_PLAYERS   28.0   113.0        3.04
14                 GAME  186.0   766.0        3.12
8             EDUCATION   26.0   111.0        3.27
25         PRODUCTIVITY   66.0   283.0        3.29
0        ART_AND_DESIGN   12.0    53.0        3.42
6         COMMUNICATION   56.0   274.0        3.89
28               SPORTS   59.0   291.0        3.93
19  MAPS_AND_NAVIGATION   21.0   104.0        3.95
27               SOCIAL   37.0   225.0        5.08
32              WEATHER   10.0    61.0        5.10
12              FINANCE   48.0   295.0        5.15
5                COMICS    8.0    50.0        5.25
21   NEWS_AND_MAGAZINES   34.0   223.0        5.56
30     TRAVEL_AND_LOCAL   30.0   200.0        5.67
16       HOUSE_AND_HOME   10.0    68.0        5.80
22            PARENTING    7.0    51.0        6.29
15   HEALTH_AND_FITNESS   36.0   274.0        6.61
1     AUTO_AND_VEHICLES    7.0    74.0        9.57
26             SHOPPING   21.0   227.0        9.81
7                DATING   19.0   212.0       10.16
13       FOOD_AND_DRINK    8.0   114.0       13.25
9         ENTERTAINMENT    2.0   142.0       70.00

In [11]:
df2.to_csv("popularity.csv")